### ISSUE TITLE
varying ASN1 types

### ISSUE THREAD

**Issue by gknocke** [Javex/libscep#13]
SCEP Attributest are defined in such a way, that every filed is of a unique type, e.g. printable string, octet string etc.
But: We also need to deal with non-specific attributes, e.g. challenge passord.
Currently, the challenge password is expected to be a printablestring which usually works. PKCS7 allows a lot of possibilities here. It can also be a ia5string or so.

When reading out attributes, all non-proprietary attributes must be treated as more generic types, such as DIRECTORY STRING. This might be challenging in the current setup.

**Comment by Javex** [comment]
According to PKCS#10 [Section 4.1](https://tools.ietf.org/html/rfc2986#section-4.1) this is contained in an attribute. An according to PKCS#9 [Section 5.4.1](https://tools.ietf.org/html/rfc2985#section-5.4) this is not clearly defined as to which type it should have. I also have no idea how to read this ASN.1 crap but I have a feeling that this part `WITH SYNTAX DirectoryString` is exactly what we are looking for (and it matches what you wrote). It also tells us that it is a single value (instead of a set). Looking at `x509h`:

```
typedef struct x509_attributes_st
    {
    ASN1_OBJECT *object;
    int single; /* 0 for a set, 1 for a single item (which is wrong) */
    union   {
        char        *ptr;
/* 0 */     STACK_OF(ASN1_TYPE) *set;
/* 1 */     ASN1_TYPE   *single;
        } value;
    } X509_ATTRIBUTE;
```

I see that we can in any way deduce the `ASN1_TYPE *single` variable. Now the question is: can we be more specific than ASN1_TYPE? The ASN1_TYPE looks like this:

```
typedef struct asn1_type_st
    {
    int type;
    union   {
        char *ptr;
        ASN1_BOOLEAN        boolean;
        ASN1_STRING *       asn1_string;
        ASN1_OBJECT *       object;
        ASN1_INTEGER *      integer;
        ASN1_ENUMERATED *   enumerated;
        ASN1_BIT_STRING *   bit_string;
        ASN1_OCTET_STRING * octet_string;
        ASN1_PRINTABLESTRING *  printablestring;
        ASN1_T61STRING *    t61string;
        ASN1_IA5STRING *    ia5string;
        ASN1_GENERALSTRING *    generalstring;
        ASN1_BMPSTRING *    bmpstring;
        ASN1_UNIVERSALSTRING *  universalstring;
        ASN1_UTCTIME *      utctime;
        ASN1_GENERALIZEDTIME *  generalizedtime;
        ASN1_VISIBLESTRING *    visiblestring;
        ASN1_UTF8STRING *   utf8string;
        /* set and sequence are left complete and still
         * contain the set or sequence bytes */
        ASN1_STRING *       set;
        ASN1_STRING *       sequence;
        ASN1_VALUE *        asn1_value;
        } value;
    } ASN1_TYPE;
```

Here we find all the stuff you mention, but no `DirectoryString`. **However**, [RFC 4517, Section 3.3.6](https://tools.ietf.org/html/rfc4517) defines `DirectoryString = 1*UTF8`. So I deduce we can always use the `ASN1_UTF8STRING` type for this.

Then again you mention IA5String and that seems to be a different type. The only question for us is: What to return. If possible, a UTF8-encoded `char *` could be great: If no more than ASCII is expected, great, no need to go any further. Since multi-byte strings (which UTF-8 is) are handled as `char *` as well, I think this would be a great return type. But only if we don't loose any necessary information. If all else fails, we can always just return the `ASN1_TYPE` pointer and let the user handle it.

**Comment by Javex** [comment]
I have looked around a bit more. I'd say we do the following: We treat it as either a printable or UTF8 string (we can check for both types). I took this idea from this java snippet:

```
            DERString str = null;

            try {
                str = DERPrintableString.getInstance((values.getObjectAt(0)));
            } catch (IllegalArgumentException ie) {
                // This was not printable string, should be utf8string then according to pkcs#9 v2.0
                str = DERUTF8String.getInstance((values.getObjectAt(0)));
            }
```

I think providing access to UTF8 and printable (I think that's ASCII) is more than enough for the most cases. But we might run into a problem, when we need to provide access to another type of value. Maybe we could encapsulate this in a union or so? Then we could easily extend this should we need to add another type.

**Comment by gknocke** [comment]
I think it would be sufficient. Maybe we will find an elegant way to treat all possible strings (teletexString, printableString, universalString, utf8String, bmpString) with a separate function. Somewhere deep in OpenSSL there must be come code for printing certificates pretty and they had do deal with the same challenge. But this has no priority.

**Comment by Javex** [comment]
Quick note: printing of attributes using `openssl req` comes down to this: https://github.com/openssl/openssl/blob/master/crypto/asn1/t_req.c#L150
