### ISSUE TITLE
requesting certs for different purposes

### ISSUE THREAD

**Issue by gknocke** [Javex/libscep#25]
I'm confused by this information from the draft:

> The pkcsPKIEnvelope for this message type is protected using the
> public key of the recipient as detailed in Section 3.1.2.  For
> example if a self-signed certificate was used to send the original
> request then this self-signed certificate's public key is used to
> encrypt the content-encryption key of the SUCCESS response's
> pkcsPKIEnvelope.

The mentioned example forces the user to use the same certificate for signing and encryption. This is in fact not recommended. Later, the following is stated:

> Since there can be multiple outstanding requests from one
> requester (for example, if different keys and different key-usages
> were used to request multiple certificates), the transaction ID must
> also be included, to disambiguate between multiple requests.

Assuming the CA limits the key-usage to signing only, SCEP would fail when staying compliant to the above example.

I can only see one solution which contributes to previous discussions: If the client uses a different encryption cert than a signing cert, he MUST include BOTH in his request (regardless which kind of request). Then, the recipient has the opportunity to use a public key for encryption provided via the request. Do you agree? However, this leads to further questions. How can the server decide which cert to use for encryption if multiple possibilities are given? Probably all of them with appropiate key-usage and validity... I'm not sure if the same holds for multiple server signing certificates.

**Comment by Javex** [comment]
This is a really interesting question. I cannot say I see a solution right now, but I'd like to limit the problem: I am pretty sure that this is not an issue for the server as the server certificate for SCEP can be uniquely created for this purpose and be allowed to have both usages. This can just be a requirement for the server by the standard.

However, the problem arises when requesting new certificates that for roles with limited key usages. From the original protocol there does not seem to be a solution as this is a case that was overlooked. So here is my suggestion:

We introduce a new flag that modifies behavior in a non-standard way. Whichever this is, it is highly likely that both client and server must be running libscep as it won't work otherwise because it is not part of the protocol.

Then we need a way to communicate this non-standard behavior between client and server. This can either be done implicity (e.g. the presence of an additional certificate) or explicitly (set an attribute on the PKCS#7 for example).

With the explicit way we could also directly communicate which certificate has to be used for signing and which for encryption. Interestingly, this could cause issues on an encryption-only certificate: What to use for signing? The client must have some valid certificate for signing... but there also has to be a relationship of some kind between the encryption and signature certificate.

In the end I propse the following: Right now, we ignore this problem, was it is not part of the standard and not an issue anywhere, right? We may tackle it later if it does become an issue and then look for a satisfying approach. Okay?

**Comment by gknocke** [comment]
For now, we can ignore the problem but we need to be aware of it. Is is possible to remain SCEP compliant with my suggestion above. It shows that we must provide the opportunity to include entire stacks of certificates when the scep standard allows it. You can have a look at 
https://github.com/Javex/libscep/blob/develop/src/message.c#L765
I implemented it in such a way, that the user can provide an arbitrary amount of certificates

**Comment by Javex** [comment]
We should check that if SCEP allows multiple certificates that we also provide the possbility to add multiple certificates instead of a single one.

**Comment by gknocke** [comment]
OK, there was a misunderstanding which makes this issue easy:
- PKCSreq does not include multiple certs, only the answer TO PKCSReq which is already implemented
- It is the servers choice which certificate he uses when encrypting the content. It comes from the outside and we dont have to deal with it. I.e: The client wants to request a signing-only certificate but has no encryption only certificate the protocol would fail since the answer kannot be encrypted. But the user cannot provide us with an encryption certificate so he cannot use it. Its just not our problem :)

**Comment by Javex** [comment]
Then we can close this, right?
